### ISSUE TITLE
Sample CSVW pipeline doesn't work aka paths should be relative to pipeline

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59#1]
## Description

When running the csvw pipeline, it fail to load the input data and mapping files. Apparently the pipeline variable `p:value "test.csv"` assumes path relative to the working directory and not to the pipeline itself.

## Current behaviour

```sh
node bin/barnard59.js run examples/parse-csvw.ttl --format text/turtle --pipeline http://example.org/pipeline/parseCsvw

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'test.csv'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

## Workaround

The example works if pipeline is changed as follows:

```diff
<parseCsvw> a p:Pipeline;
  p:variables [
    p:variable [
      p:name "filename";
-      p:value "test.csv";
+      p:value "examples/test.csv";
    ], [
      p:name "metadata";
-      p:value "test.csv-metadata.json";
+      p:value "examples/test.csv-metadata.json";
    ]
  ];
  p:steps [
    p:stepList ( <readFile> <parse> <serialize> )
  ].
```

**Comment by bergos** [comment]
Oh, maybe I run the example inside the examples folder. I changed it and also added it to the readme in this commit: 49bbae421073e81233668f82a6e190d92ed1dd58

**Comment by tpluscode** [comment]
Thanks for changing the example and adding a snippet.

Still, maybe I don't yet see a typical use case for barnard pipelines but wouldn't relative paths make sense by default? With an option to override how they are resolved?

```
node barnard.js run pipeline.json --root /some/path
```

Especially that it already works this way with relative `code:link <file:../node_modules/barnard59-base#map>`. I see it's a different semantic but surprising nonetheless

**Comment by bergos** [comment]
Both cases could make sense. Especially generic subpipelines could be designed to use static files from a static folder, but other input from the cwd. I created an issue for the schema resolver stuff #2.
