### ISSUE TITLE
Make namespaces resolvable

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59#11]
It should be possible to fetch the http URLs from the `code` and `pipeline` namespace and get a response including a readable labe.

**Comment by bergos** [comment]
[code](https://code.described.at/) and [pipeline](https://pipeline.described.at/) namespace is reachable now. Automatic deploy needs to be configured.

**Comment by vhf** [comment]
I think this can be closed @bergos . If that's ok for you I'll merge the branches `editor` to `master` on both described-at repos.
