### ISSUE TITLE
Step stream type validation

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59#113]
For the pipelines the type (Readable/Writable) is defined as `rdf:type` triple. It should be validated that the first and last stream, defined in the `stepList` matches the type definition. Maybe also `objectMode` can be validated.

**Comment by tpluscode** [comment]
I considered using SHACL for such validation but lists are difficult. Might try n3 instead

cc @giacomociti

**Comment by giacomociti** [comment]
not sure about the exact validation requirements but yes, lists in n3 are much easier. They even have built-ins for first and last: https://n3-editor.herokuapp.com/n3/editor/s/gTbIlHoU
