### ISSUE TITLE
Preserve typing of variables

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59#116]
## Description 

I notice that data type of pipeline variables is ignored. For example, which may not be "real-life" enough but so be it, I was trying to pass a parameter to `JSON.stringify` as shown in the below excerpt from the modified [csvw example](https://github.com/zazuko/barnard59-main/blob/master/examples/parse-csvw.ttl)

```
<parseCsvw> a p:Pipeline;
  p:variables [
    p:variable [
      p:name "jsPad";
      p:value 5
    ]
  ];
  p:steps [
    p:stepList ( <readFile> <parse> <serialize> <stringify> )
  ].

<stringify> a p:Step;
  p:operation [
    code:link <node:barnard59-base#map>;
    code:type code:ecmaScript
  ];
  p:arguments ("obj => JSON.stringify(obj, null, this.variables.get('jsPad'))"^^code:ecmaScript).
```

## Current behaviour

Turns out that this doesn't work, because the third argument of `JSON.stringify` has to be a number. Despite `jsPad` variable being typed as integer in the pipeline graph, it is always a string in `this.variables` map.

## Expected behaviour

For starters, at least numeric and booleans should be preserved as matching JS types

**Comment by bergos** [comment]
Yes, for sure we need this. SimpleRDF does this already, but there should be a seprate package just doing the rdfjs Literal to JS native mapping. Any proposals for a package name?

**Comment by tpluscode** [comment]
Something like `@rdfjs/native-type-mapper` that would take a (literal) node and return a native object?

Going way beyond, but would it be limited to literal nodes only?

**Comment by bergos** [comment]
The rdfjs package should cover only literals and standard types (xsd). Otherwise I expect to much discussion. Lets stay pragmatic.
