### ISSUE TITLE
Variables from CLI should overwrite values from the pipeline definition

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59#12]
Currently the variables from the pipeline definition are used if the same variables is also given via CLI. The variables from the CLI should have a higher priority, so it's possible to use a default from the definition and overwrite it via CLI parameter.

**Comment by tpluscode** [comment]
Is this still an issue @ktk? I looked into `barnard59-core` and it seems to be working as described here.

Please reopen if you feel it needs attention
