### ISSUE TITLE
Add monitoring operation

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59#121]
There should be an operation that logs in specific intervals the throughput at a specific point in the pipeline. It should be available as raw and object operation.

**Comment by bergos** [comment]
A similar feature was implemented in an old version of barnard:

- [count](https://github.com/zazuko/barnard59-legacy/blob/master/lib/count.js)
- [size](https://github.com/zazuko/barnard59-legacy/blob/master/lib/size.js)
- [speed](https://github.com/zazuko/barnard59-legacy/blob/master/lib/speed.js)

**Comment by cristianvasquez** [comment]
Hi @bergos, to which repository does this need to be added?

**Comment by cristianvasquez** [comment]
Pull request at: https://github.com/zazuko/barnard59-base/pull/26

**Comment by cristianvasquez** [comment]
Smaller pull request at: https://github.com/zazuko/barnard59-base/pull/28

**Comment by tpluscode** [comment]
As discussed with @cristianvasquez @giacomociti @mchlrch, we propose that instead of implementing specialized monitoring steps, there should be a built-in feature to allow observing existing steps in a pipeline.
