### ISSUE TITLE
forEach should check if the second argument is a string

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59#122]
The second argument of the `forEach` operation is the key of the variable to store the chunks for each loop. Any value besides a string doesn't make sense. In 0.x it was possible to provide a function. People updating their pipelines to run with 1.x may stumble over this change. That's why a readable error message would be very useful.

**Comment by tpluscode** [comment]
@magdasalatka do you remember if and when you needed this improvement?

**Comment by magdasalatka** [comment]
IIRC that was about poor error handling in barnard. Basically the errors of what happens within `forEach` are/were not forwarded.
