### ISSUE TITLE
Operations structure

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59#16]
# Barnard59 Operations

# General
- **barnard59-base**
  - [ ] ~**after**: Run a sub pipeline after all data was processed. Acts like PassThrough. (We need to have a closer look at the concept)~
  - [ ] ~**before**: Run a sub pipeline after all data was processed. Acts like PassThrough. (We need to have a closer look at the concept)~
  - [x] **concat**: Concats multiple streams into a single stream. Can be also used to glue sub pipelines together.
  - [x] **filter**: Just like `Array.prototype.filter`, just for streams.
  - [x] **flatten**: Separates incoming arrays into it's elements.
  - [x] **map**: Just like `Array.prototype.map`, just for streams.
  - [x] **nul**: `/dev/null` for streams.
  - [x] **slice**: Uses the chunk index as filter. Can be used as offset and/or limit.
  - [x] **stdout**: Writes to `stdout`. Acts like PassThrough.
  - [x] **toString**: Calls `.toString` for each chunk. 
  - json
    - [x] **parse**: Calls `JSON.parse` for each chunk.
    - [x] **stringify**: Calls `JSON.stringify` for each chunk.
- **barnard59-rdf**
  - [x] **setGraph**: Sets the graph part of an RDF/JS Quad.
- **barnard59-shell**
  - [ ] **plain**: Wraps a shell command into a duplex stream forwarding `stdin` & `stdout`.
  - [ ] **after**: Maybe deprecated by `barnard59-base#after`
  - [ ] **before**: Maybe deprecated by `barnard59-base#before`

# Formats

- **barnard59-jsonld**
  - [x] **parse**: Parses JSON-LD data provided as string stream. 
  - [x] **parse.object**: Parses JSON-LD data provided as full object per chunk.
  - [x] **serialize**: Serializes quads to JSON-LD.
- **barnard59-ntriples**
    - [ ] **parse**: Parses N-Triples data. 
    - [ ] **serialize**: Serializes quads to N-Triples.
- **barnard59-rdfxml**
  - [ ] **parse**: Parses RDF/XML data. 
- **barnard59-turtle**
    - [ ] **parse**: Parses Turtle data. 
    - [ ] **serialize**: Serializes quads to Turtle.

# Protocols

- **barnard59-graph-store**
  - [ ] **delete**: Makes a Graph Store DELETE request.
  - [ ] **get**: Makes a Graph Store GET request.
  - [x] **post**: Makes a Graph Store POST request.
  - [x] **put**: Makes a Graph Store PUT request.
- **barnard59-http**
  - [x] **get**: Makes a HTTP GET request.
  - [x] **post**: Makes a HTTP POST request.
  - [ ] **put**: Makes a HTTP PUT request.
- **barnard59-kafka**
  - [x] **consumer**: Reads messages from a Kafka queue.
  - [x] **consumerRaw**: Reads messages from a Kafka queue and processes the full message, including topic. Useful if the topic selector catches multiple topics.
  - [x] **producer**: Writes message to a Kafka queue.
- **barnard59-mqtt**
  - [x] **subscribe**: Subscribes to a MQTT broker.
  - [x] **subscribeRaw**: Subscribes to MQTT broker and processes the full message, including topic. Useful if the topic selector catches multiple topics.
- **barnard59-sparql**
  - [ ] **ask**: Makes a SPARQL ASK query and returns the result as a single boolean chunk stream. 
  - [ ] **construct**: Makes a SPARQL CONSTRUCT query and returns the results as a RDF/JS Quad stream.
  - [ ] **insert**: Makes a SPARQL INSERT query and writes the given quads to the SPARQL endpoint.
  - [x] **select**: Makes a SPARQL SELECT query and returns the result as an object with variable/value pairs. The values are provided as RDF/JS Term objects.

**Comment by tpluscode** [comment]
I understand correctly, this serves as an outline for documentation pages?

**Comment by bergos** [comment]
This will be the package structure. Could also make sense for the documentation, as it's hopefull well enough structured. So each `barnard59-*` is a separate package.

**Comment by ktk** [comment]
Great list thanks, I would like to add two generic feature requests, we can discuss how to approach that later:

* RML converter, mainly for XML based input (`carml` would be my priority)
* SHACL processor. RDFUnit or alike as implementation
