### ISSUE TITLE
Implement a SHACL step

### ISSUE THREAD

**Issue by ktk** [zazuko/barnard59#26]
From time to time I break stuff and don't notice it so the pipeline writes incomplete data into the endpoints.

That could be solved by providing a SHACL step so one can define tests that have to run through before the data is uploaded.

We need to evaluate what engine makes most sense for it, preferably something streaming.

**Comment by bergos** [comment]
I think SHACL + stream processing is not a good combination. It will always require some kind of buffering. Running a SHACL validation on a full dataset is maybe also not a good idea. I think it would work best by creating datasets based on new subject  or rdf:type and only validate that subset.

**Comment by tpluscode** [comment]
https://github.com/zazuko/barnard59-validate-shacl
