### ISSUE TITLE
Add static files to the stream

### ISSUE THREAD

**Issue by ktk** [zazuko/barnard59#27]
In some pipelines a static RDF file needs to be added to the pipeline, containing for example metadata that should be added. There should be an easy way to add that to a pipeline.

**Comment by ktk** [comment]
I could do that in some pipelines but not all scenarios support that right now: https://github.com/Staatsarchiv-Basel-Stadt/RDF-Pipeline/blob/master/pipelines/staatsarchiv.ttl#L46

**Comment by ktk** [comment]
Am I right that this is basically #28 ?

**Comment by tpluscode** [comment]
This has been implemented in `barnard59-rdf/fs.js` https://github.com/zazuko/barnard59/issues/98#issuecomment-1552819728
