### ISSUE TITLE
Load files from the local file system as arguments

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59#31]
In some cases it would be useful to read the content of files on the local file system. For example a ssh key can be loaded like this:

```
"${require('fs').readFileSync('/full/path/myKeyFile.key').toString()}"^^code:EcmaScriptTemplateLiteral
```

But it would be useful to have a datatype + loader that handles it:

```
"/full/path/myKeyFile.key"^^p:FileContent
```

It should also work with variables:

```
"keyFilename"^^p:VariableFileContent
```

**Comment by tpluscode** [comment]
This could also be implemented as as stream itself. The SHACL validation step does that to [load the shapes graph](https://github.com/zazuko/barnard59-validate-shacl/blob/a5ecc1b0f843d5de17355935eed74a11c546abea/validate.js#L55). That is not as nice as a synchronous loader to plug in directly to the function but avoids the risk of loading large files to memory

The problem of using a pipeline is verbosity, requiring a more complex setup. Given the original example 

```turtle
<step>
  a :Step ;
  code:arguments (
    <loadStepFile>
  ) ;
.

<loadStepFile> a :Pipeline, :Readable ;
  :steps [ :stepList (
    [ 
      code:implementedBy [ code:link <node:fs#createReadStream> ] ;
      code:arguments ( "/full/path/myKeyFile.key" )
    ] 
  ) ] ;
.
```

Hypothetically, #85 could be a solution, where the `<loadStepFile>` becomes a reusable building block
