### ISSUE TITLE
RDF Validator

### ISSUE THREAD

**Issue by ktk** [zazuko/barnard59#40]
We need to be able to check if the RDF generated is valid. Basically like `riot --validate` does, maybe it could even use that. IIRC this is supporting streaming.

**Comment by tpluscode** [comment]
On second or third thought, maybe this is not within the scope of a pipeline.

riot verifies syntax, which is by product of serialising. That may or may not be part of a pipeline.

**Comment by ktk** [comment]
Agreed and we do it with riot everywhere by now so I'm closing this.
