### ISSUE TITLE
Populate variables from process.env

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59#42]
My proposal is to transparently set pipeline variables with those set to the environment.

While it is possible to use `process.env.VAR` in template string it breaks the variables feature of the pipeline. I would have them work with least effort possible:

```turtle
@prefix : <https://pipeline.described.at/> .

_:vars :variable
  [ a :Variable; :name "sourceDir"; :value "source"; :envVariable "MAPPING" ] .

<> a :Pipeline ;
   :variables _:vars .
```

The `envVariable` creates a mapping between a pipeline variable and environment variable. If the variable `MAPPING` is defined it will be used for `sourceDir` in the pipeline.

Variables passed explicitly by `--variable` CLI parameter take precedence. So we have 3 possible scenarios:

```
barnard59 run pipeline.ttl
# default value 
# sourceDir="source"

MAPPING=from barnard59 run pipeline.ttl
# env value 
# sourceDir="from"

MAPPING=from barnard59 run --variable sourceDir=input pipeline.ttl
# --variable takes precedence before ENV
# sourceDir=input
```

**Comment by tpluscode** [comment]
@ktk @l00mi you might want to weigh in

While we discussed with @bergos in general and disagreed a little bit I propose the above as a solution most friendly to the end consumer. Anywhere in the definition the pipeline variables would be used and only a simple mapping from ENV is required once.

**Comment by l00mi** [comment]
I have no strong opinion here, what would the disagreement be about?

**Comment by ktk** [comment]
I think I see the point as well but I am not sure where the disagreement is?

**Comment by tpluscode** [comment]
I think @bergos proposed a more imperative approach. It was difficult to discuss without some code example so I created this to transfer my idea to something palatable

**Comment by BenjaminHofstetter** [comment]
I like the proposed approach because when I read it then I can imagine what will happen.

**Comment by bergos** [comment]
A different approach described in #46 was implemented.
