### ISSUE TITLE
Set compression for fetch

### ISSUE THREAD

**Issue by ktk** [zazuko/barnard59#60]
Not sure which repo would be the right place so I create it here.

We fetch and write large datasets and as far as I understand so far without setting the compression header in fetch.

I would propose to enable compression by default or at least make it an option to set in pipelines that specific/all requests are doing compression. This reduces traffic transferred a lot in some of the use-cases we have.

This should be used both for graph store protocol & fetches for getting things like CSV files on the web.

**Comment by l00mi** [comment]
https://control.vshn.net/tickets/SBAR-436

**Comment by bergos** [comment]
It's already enabled by default in node-fetch (nodes `http` module in general).
